import type { Metadata } from "next";
import { inter } from "@/app/fonts";
import "./globals.css";
// import Navbar from "./ui/navbar/navbar";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
  keywords: "Next, React, Typescript",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
